[versions]
kotlin = "2.1.20"
kotlinter = "5.0.1"
central = "1.2.8"
dokka = "2.0.0"
jline = "3.29.0"
jansi = "2.4.1"

[libraries]
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
central = { id = "cn.lalaki.central", version.ref = "central"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
